<?php

namespace Vyper\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
    public function myFindAll()
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.deleted = false');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function getSquare($locale, $adType)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder
            ->where('a.deleted = false')
            ->andWhere('a.live = true')
            ->andWhere('a.locale = :locale')
            ->setParameter('locale', $locale)
            ->andWhere('a.type = :type')
            ->setParameter('type', $adType);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
